{{- range $name, $app := .Values.helmCharts -}}
{{ if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default $name .name }}-{{ $.Values.global.team }}-{{ $.Values.global.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    team: green
spec:
  project: {{ $.Values.global.spec.project }}
  sources:
  - repoURL:  {{ default $.Values.global.spec.source.repoURL .repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    {{- if hasKey . "chart"}}
    chart: {{ .chart }}
    {{- else if hasKey . "path"}}
    path: {{ .path }}
    {{- else }}
    path: apps/{{ default $name .name }}
    {{- end }}
    helm:
      valueFiles:
      - $valuesRepo/values/{{ default $name .name }}/values-{{ $.Values.global.env }}.yaml
  - repoURL: {{ $.Values.global.spec.values.repoURL }}
    targetRevision: {{ default $.Values.global.spec.values.targetRevision .valuesTargetRevision }}
    ref: valuesRepo
  destination:
    namespace: {{ default $.Values.global.spec.destination.namespace .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if default $.Values.global.automated .automated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- end }}
{{- end }}
